### PR TITLE
Temporarily switch from apparition to cuprite

### PR DESCRIPTION
**Pull request by elia**
This is a workaround for https://github.com/twalpole/apparition/issues/64.

### CODE REVIEW

**Review by seand7565 — APPROVED** [review]
Looks great! I'm getting a lot of cop violations locally, but nothing breaking - and I'd prefer a few cop violations to a broken spec, so I'm approving this. Here's what I got:

```ruby
Offenses:

app/controllers/solidus_paypal_commerce_platform/orders_controller.rb:45:101: C: Metrics/LineLength: Line is too long. [103/100] (https://rubystyle.guide#80-character-limits)
        respond_with(@order, default_template: 'spree/api/orders/expected_total_mismatch', status: 400)
                                                                                                    ^^^
app/controllers/solidus_paypal_commerce_platform/payments_controller.rb:13:101: C: Metrics/LineLength: Line is too long. [113/100] (https://rubystyle.guide#80-character-limits)
        return redirect_to checkout_state_path(@order.state), notice: "Invalid order confirmation data passed in"
                                                                                                    ^^^^^^^^^^^^^
app/helpers/solidus_paypal_commerce_platform/button_options_helper.rb:6:101: C: Metrics/LineLength: Line is too long. [104/100] (https://rubystyle.guide#80-character-limits)
      [["Gold", "gold"], ["Blue", "blue"], ["Silver", "silver"], ["White", "white"], ["Black", "black"]]
                                                                                                    ^^^^
app/models/solidus_paypal_commerce_platform/gateway.rb:22:101: C: Metrics/LineLength: Line is too long. [106/100] (https://rubystyle.guide#80-character-limits)
      request.request_body(amount: { currency_code: options[:currency], value: Money.new(money).dollars })
                                                                                                    ^^^^^^
app/models/solidus_paypal_commerce_platform/gateway.rb:46:101: C: Metrics/LineLength: Line is too long. [106/100] (https://rubystyle.guide#80-character-limits)
      request.request_body(amount: { currency_code: options[:currency], value: Money.new(money).dollars })
                                                                                                    ^^^^^^
app/models/solidus_paypal_commerce_platform/paypal_address.rb:46:101: C: Metrics/LineLength: Line is too long. [101/100] (https://rubystyle.guide#80-character-limits)
      if state = country.states.find_by(abbr: state_name) || country.states.find_by(name: state_name)
                                                                                                    ^
app/models/solidus_paypal_commerce_platform/pricing_options.rb:6:101: C: Metrics/LineLength: Line is too long. [102/100] (https://rubystyle.guide#80-character-limits)
      SolidusPaypalCommercePlatform::PaymentMethod.active.map(&:cache_key_with_version).sort + [super]
                                                                                                    ^^
app/models/solidus_paypal_commerce_platform/wizard.rb:27:101: C: Metrics/LineLength: Line is too long. [118/100] (https://rubystyle.guide#80-character-limits)
      URI("https://#{SolidusPaypalCommercePlatform.config.env_domain}/bizsignup/partner/entry?#{parameters.to_query}")
                                                                                                    ^^^^^^^^^^^^^^^^^^
bin/rails-sandbox:8:33: C: Style/AndOr: Use || instead of or. (https://rubystyle.guide#no-and-or-or)
    system "#{__dir__}/sandbox" or begin
                                ^^
lib/generators/solidus_paypal_commerce_platform/install/install_generator.rb:23:101: C: Metrics/LineLength: Line is too long. [105/100] (https://rubystyle.guide#80-character-limits)
        insert_into_file File.join('config', 'routes.rb'), after: "Rails.application.routes.draw do\n" do
                                                                                                    ^^^^^
lib/solidus_paypal_commerce_platform/client.rb:52:9: C: Layout/IndentFirstArgument: Indent the first argument one step more than AccessTokenAuthorizationRequest.new(.
        environment: client.environment, ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/solidus_paypal_commerce_platform/client.rb:58:9: C: Layout/IndentFirstArgument: Indent the first argument one step more than FetchMerchantCredentialsRequest.new(.
        access_token: access_token, ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/solidus_paypal_commerce_platform/configuration.rb:22:101: C: Metrics/LineLength: Line is too long. [106/100] (https://rubystyle.guide#80-character-limits)
      self.state_guesser_class = "SolidusPaypalCommercePlatform::StateGuesser" unless @state_guesser_class
                                                                                                    ^^^^^^
lib/solidus_paypal_commerce_platform/configuration.rb:50:101: C: Metrics/LineLength: Line is too long. [103/100] (https://rubystyle.guide#80-character-limits)
        raise InvalidEnvironment, "Unable to guess the PayPal env, please set #{self}.env= explicitly."
                                                                                                    ^^^
lib/solidus_paypal_commerce_platform/configuration.rb:67:101: C: Metrics/LineLength: Line is too long. [101/100] (https://rubystyle.guide#80-character-limits)
      @partner_client_id ||= ENV['PAYPAL_PARTNER_CLIENT_ID'] || DEFAULT_PARTNER_CLIENT_ID[env.to_sym]
                                                                                                    ^
lib/solidus_paypal_commerce_platform/engine.rb:16:101: C: Metrics/LineLength: Line is too long. [119/100] (https://rubystyle.guide#80-character-limits)
    initializer "solidus_paypal_commerce_platform.add_payment_method", after: "spree.register.payment_methods" do |app|
                                                                                                    ^^^^^^^^^^^^^^^^^^^
lib/solidus_paypal_commerce_platform/engine.rb:18:101: C: Metrics/LineLength: Line is too long. [104/100] (https://rubystyle.guide#80-character-limits)
      SolidusPaypalCommercePlatform::PaymentMethod.allowed_admin_form_preference_types << :paypal_select
                                                                                                    ^^^^
lib/solidus_paypal_commerce_platform/engine.rb:19:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
      Spree::PermittedAttributes.source_attributes.concat [:paypal_order_id, :authorization_id, :paypal_email]
                                                                                                    ^^^^^^^^^^
lib/solidus_paypal_commerce_platform/engine.rb:22:101: C: Metrics/LineLength: Line is too long. [111/100] (https://rubystyle.guide#80-character-limits)
    initializer "solidus_paypal_commerce_platform.add_wizard", after: "spree.register.payment_methods" do |app|
                                                                                                    ^^^^^^^^^^^
lib/solidus_paypal_commerce_platform/engine.rb:35:101: C: Metrics/LineLength: Line is too long. [102/100] (https://rubystyle.guide#80-character-limits)
      SolidusWebhooks.config.register_webhook_handler :solidus_paypal_commerce_platform, ->(payload) {
                                                                                                    ^^
spec/features/backend/new_payment_method_spec.rb:9:7: C: Layout/IndentFirstArrayElement: Use 2 spaces for indentation in an array, relative to the first position after the preceding left parenthesis.
      "PayPal Commerce Platform",
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/features/backend/new_payment_method_spec.rb:14:5: C: Layout/IndentFirstArrayElement: Indent the right bracket the same as the first position after the preceding left parenthesis.
    ])
    ^
spec/features/frontend/cart_spec.rb:26:101: C: Metrics/LineLength: Line is too long. [108/100] (https://rubystyle.guide#80-character-limits)
      expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^
spec/features/frontend/cart_spec.rb:33:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^^^
spec/features/frontend/checkout_spec.rb:27:101: C: Metrics/LineLength: Line is too long. [108/100] (https://rubystyle.guide#80-character-limits)
      expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^
spec/features/frontend/checkout_spec.rb:34:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^^^
spec/features/frontend/checkout_spec.rb:52:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        find(:xpath, "//input[@id='payments_source_paypal_order_id']", visible: false).set SecureRandom.hex(8)
                                                                                                    ^^^^^^^^^^
spec/features/frontend/checkout_spec.rb:60:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        find(:xpath, "//input[@id='payments_source_paypal_order_id']", visible: false).set SecureRandom.hex(8)
                                                                                                    ^^^^^^^^^^
spec/features/frontend/checkout_spec.rb:61:101: C: Metrics/LineLength: Line is too long. [104/100] (https://rubystyle.guide#80-character-limits)
        find(:xpath, "//input[@id='payments_source_paypal_email']", visible: false).set "fake@email.com"
                                                                                                    ^^^^
spec/features/frontend/checkout_spec.rb:68:101: C: Metrics/LineLength: Line is too long. [105/100] (https://rubystyle.guide#80-character-limits)
      before { allow_any_instance_of(PayPal::PayPalHttpClient).to receive(:execute) { failed_response } }
                                                                                                    ^^^^^
spec/features/frontend/checkout_spec.rb:73:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        find(:xpath, "//input[@id='payments_source_paypal_order_id']", visible: false).set SecureRandom.hex(8)
                                                                                                    ^^^^^^^^^^
spec/features/frontend/product_spec.rb:22:101: C: Metrics/LineLength: Line is too long. [108/100] (https://rubystyle.guide#80-character-limits)
      expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^
spec/features/frontend/product_spec.rb:29:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
        expect(paypal_script_options).to include("client-id=#{paypal_payment_method.preferences[:client_id]}")
                                                                                                    ^^^^^^^^^^
spec/features/frontend/product_spec.rb:36:101: C: Metrics/LineLength: Line is too long. [105/100] (https://rubystyle.guide#80-character-limits)
        allow_any_instance_of(Spree::Core::ControllerHelpers::Store).to receive(:current_store) { store }
                                                                                                    ^^^^^
spec/features/frontend/product_spec.rb:61:101: C: Metrics/LineLength: Line is too long. [101/100] (https://rubystyle.guide#80-character-limits)
        expect(page.evaluate_script("Spree.current_order_token")).to eq Spree::Order.last.guest_token
                                                                                                    ^
spec/models/solidus_paypal_commerce_platform/payment_method_spec.rb:49:101: C: Metrics/LineLength: Line is too long. [109/100] (https://rubystyle.guide#80-character-limits)
      expect_request(:AuthorizationsCaptureRequest).to receive(:new).with(authorization_id).and_call_original
                                                                                                    ^^^^^^^^^
spec/models/solidus_paypal_commerce_platform/payment_source_spec.rb:22:101: C: Metrics/LineLength: Line is too long. [107/100] (https://rubystyle.guide#80-character-limits)
    allow_any_instance_of(SolidusPaypalCommercePlatform::Client).to receive(:execute) do |_client, request|
                                                                                                    ^^^^^^^
spec/requests/solidus_paypal_commerce_platform/wizard_controller_spec.rb:11:101: C: Metrics/LineLength: Line is too long. [118/100] (https://rubystyle.guide#80-character-limits)
        authCode: "PFc4d2vp4DVfHqcnEHbGAA12C_H29U39NM_vmQrZBPzdLcxA12Br-GzjbliqXGu3AG6Gfwo5G9GTal6REkcKGMREc9fPsR_wv",
                                                                                                    ^^^^^^^^^^^^^^^^^^
spec/requests/solidus_paypal_commerce_platform/wizard_controller_spec.rb:12:101: C: Metrics/LineLength: Line is too long. [101/100] (https://rubystyle.guide#80-character-limits)
        sharedId: "awj45zMAy1XonxWfgIhjjGHZGAPStkZFzXp4bfe1QmNWA-9DL6HkpklD0skHig4vVF7zVZD8Uwy5Qop4",
                                                                                                    ^
spec/requests/solidus_paypal_commerce_platform/wizard_controller_spec.rb:18:101: C: Metrics/LineLength: Line is too long. [110/100] (https://rubystyle.guide#80-character-limits)
      expect_any_instance_of(SolidusPaypalCommercePlatform::Client).to receive(:execute) do |_client, request|
                                                                                                    ^^^^^^^^^^
```

**Comment by elia** [comment]
@seand7565 can it be that you're running a rubocop from outside the bundle?

**Comment by seand7565** [comment]
I don't think so, I'm running bundle exec rubocop. What's weird is it's also not recognizing some of the new cops. I made sure my rubocop version was updated. 🤔 

```ruby
seandenny@MacBook-Pro solidus_paypal_commerce_platform % bundle exec rubocop
Warning: unrecognized cop Layout/FirstArgumentIndentation found in .rubocop.yml
Warning: unrecognized cop Layout/FirstArrayElementIndentation found in .rubocop.yml
Warning: unrecognized cop RSpec/MultipleMemoizedHelpers found in .rubocop.yml
Warning: unrecognized cop Rails/Inquiry found in .rubocop.yml
Warning: unrecognized cop Rails/ActiveRecordCallbacksOrder found in .rubocop.yml
Warning: unrecognized cop Rails/FindById found in .rubocop.yml
Warning: unrecognized cop Rails/MailerName found in .rubocop.yml
Warning: unrecognized cop Rails/MatchRoute found in .rubocop.yml
Warning: unrecognized cop Rails/NegateInclude found in .rubocop.yml
Warning: unrecognized cop Rails/Pluck found in .rubocop.yml
Warning: unrecognized cop Rails/PluckInWhere found in .rubocop.yml
Warning: unrecognized cop Rails/RenderInline found in .rubocop.yml
Warning: unrecognized cop Rails/RenderPlainText found in .rubocop.yml
Warning: unrecognized cop Rails/ShortI18n found in .rubocop.yml
Warning: unrecognized cop Rails/WhereExists found in .rubocop.yml
Inspecting 60 files
..CC....C..C..C.C.C.........C...C..CCC.....CCCC...CC.....C..
```

**Comment by elia** [comment]
🤔 this straight after a `bundle update` or `bin/setup`?

I'm getting this:

```
solidus_paypal_commerce_platform:master ⤑ be rubocop -ESP
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Rails/AfterCommitOverride (2.8)
 - Rails/SquishedSQLHeredocs (2.8)
 - Rails/WhereNot (2.8)
 - Performance/Sum (1.8)
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 62 files
..............................................................

62 files inspected, no offenses detected
solidus_paypal_commerce_platform:master ⤑                                                                  ~/C/N/solidus_paypal_commerce_platform
```

**Pull request merged**
