### PR TITLE
Wizard#logo use `image_path` over `image_url`.

### PR DESCRIPTION
**Pull request by essn**
- `image_path` computes the asset path including configured asset host
  and digest. This fixes an issue where compiled assets and assets
  stored in a CDN where not referenced correctly.

### CODE REVIEW

**Comment by essn** [comment]
https://github.com/solidusio-contrib/solidus_paypal_commerce_platform/issues/130#issue-901726959

**Comment by jakemumu** [comment]
I think this one is unrelated to 130 -- but still was a valid error

**Comment by kennyadsl** [comment]
@essn can you make an example of before and after this? I was expecting `image_url` to return the absolute URL already.

**Comment by jakemumu** [comment]
@kennyadsl -- not sure if Jesse saw this, I can dig it out, but the main gist was when using a CDN for asset hosting with Solidus + this extension, the asset host was not being prepended to the relative path for the file. 

Here's a snippet just from console on production: 

```
Running rails console on ⬢ minimal-audio... up, run.7625 (Standard-1X)
Loading production environment (Rails 6.0.3.6)
irb(main):001:0> ActionController::Base.helpers.image_url(::Spree::Config[:admin_interface_logo])
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `protocol' for nil:NilClass)
irb(main):002:0> ActionController::Base.helpers.image_path(::Spree::Config[:admin_interface_logo])
=> "//minimal-audio-herokuapp-com.global.ssl.fastly.net/assets/logo-403807da23d29c35a2cff3062bf2b331a3cdac8d9ed6d26a2da845f7871edcfd.svg"
```

**Comment by essn** [comment]
I was trying to get together a good test, but if you change the asset host in the test environment file, run the suite, and look at the url generated you can see the asset host isn't included.

If you stub out the asset host in the test ENV and regex match the generated URL it will fail. If anyone knows a good way to mock that I can add a spec.

**Comment by essn** [comment]
The quick and dirty way for me was to modify the test env file to use an arbitrary asset host `config.action_controller.asset_host = 'https://some.asset.host'` and using `pry` (or similar tool) check tat the URL generated by `Wizard#logo` included that host. Without the patch it did not. With the patch it did.

**Review by kennyadsl — APPROVED** [review]

**Pull request merged**
